import type { NextApiRequest, NextApiResponse } from "next";
import { Recipes } from "../../typs/product";

const recipes: Recipes = [
  {
    image: "assets/recipe/recipy (1).jfif",
    name: "Fish with rice",
    discription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In excepturi necessitatibus animi officia corrupti laudantium nesciunt saepe rerum dolores corporis odio quae obcaecati doloribus magnam, praesentium aliquam cumque culpa! Iste modi quis totam excepturi? Dolore accusamus, incidunt error ducimus inventore sit eveniet iusto numquam exercitationem ipsam itaque at harum quibusdam nobis fugit beatae distinctio cumque molestias illum reiciendis quisquam enim dolorem. Ex assumenda tempore blanditiis beatae quidem repellat non quos ea, velit, et quo? Quo libero deserunt dolor atque dolore aperiam velit sapiente voluptatum veniam blanditiis? Atque qui iure quaerat rem quia suscipit esse incidunt possimus, quasi laudantium optio temporibus nulla ipsam laborum aliquam fugiat provident, deserunt, voluptas neque praesentium labore sequi. Aspernatur fugiat blanditiis dolorem assumenda debitis explicabo reprehenderit, laborum impedit dolor, modi alias illum dolorum quae culpa nisi corporis? Veniam provident nisi ab eos doloremque iure sequi, magnam cupiditate libero odit, tenetur iste consequatur accusantium, perferendis consectetur similique ipsam praesentium fugiat! Soluta, doloribus sequi! Suscipit magni esse cupiditate labore animi consequuntur dolorum iure quae sit, ullam omnis ad nesciunt nam! Tempore sunt ea temporibus rem pariatur dolor perspiciatis maiores adipisci magnam deserunt facere quibusdam sed impedit velit, reiciendis numquam fugiat delectus quaerat. Labore quas in eveniet earum autem.",
    ingredients: [
      "Sliced avocado",
      "1 bay leaf",
      "1/2 cup bittersweet chocolate chips (I like Ghirardelli)",
      "1 cup black beans",
      "Black Beans",
      "1 (15 oz.) can red kidney beans, drained and rinsed",
      "1 (28 oz.) can crushed tomatoes",
      "Toasted corn or flour tortillas for scooping",
      "Chili",
      "2 teaspoons chili powder (mine is a bit on the hot side)",
      "Chopped fresh cilantro",
      "2 garlic cloves, chopped",
      "1 teaspoon ground coriander",
      "2 teaspoons ground cumin",
      "1/2 teaspoon ground black pepper",
      "Shredded Monterey Jack cheese",
      "1 tablespoon olive oil",
    ],
  },
  {
    image: "/assets/recipe/recipy (1).png",
    name: "Khichuri Buna",
    discription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In excepturi necessitatibus animi officia corrupti laudantium nesciunt saepe rerum dolores corporis odio quae obcaecati doloribus magnam, praesentium aliquam cumque culpa! Iste modi quis totam excepturi? Dolore accusamus, incidunt error ducimus inventore sit eveniet iusto numquam exercitationem ipsam itaque at harum quibusdam nobis fugit beatae distinctio cumque molestias illum reiciendis quisquam enim dolorem. Ex assumenda tempore blanditiis beatae quidem repellat non quos ea, velit, et quo? Quo libero deserunt dolor atque dolore aperiam velit sapiente voluptatum veniam blanditiis? Atque qui iure quaerat rem quia suscipit esse incidunt possimus, quasi laudantium optio temporibus nulla ipsam laborum aliquam fugiat provident, deserunt, voluptas neque praesentium labore sequi. Aspernatur fugiat blanditiis dolorem assumenda debitis explicabo reprehenderit, laborum impedit dolor, modi alias illum dolorum quae culpa nisi corporis? Veniam provident nisi ab eos doloremque iure sequi, magnam cupiditate libero odit, tenetur iste consequatur accusantium, perferendis consectetur similique ipsam praesentium fugiat! Soluta, doloribus sequi! Suscipit magni esse cupiditate labore animi consequuntur dolorum iure quae sit, ullam omnis ad nesciunt nam! Tempore sunt ea temporibus rem pariatur dolor perspiciatis maiores adipisci magnam deserunt facere quibusdam sed impedit velit, reiciendis numquam fugiat delectus quaerat. Labore quas in eveniet earum autem.",
    ingredients: [
      "Sliced avocado",
      "1 bay leaf",
      "1/2 cup bittersweet chocolate chips (I like Ghirardelli)",
      "1 cup black beans",
      "Black Beans",
      "1 (15 oz.) can red kidney beans, drained and rinsed",
      "1 (28 oz.) can crushed tomatoes",
      "Toasted corn or flour tortillas for scooping",
      "Chili",
      "2 teaspoons chili powder (mine is a bit on the hot side)",
      "Chopped fresh cilantro",
      "2 garlic cloves, chopped",
      "1 teaspoon ground coriander",
      "2 teaspoons ground cumin",
      "1/2 teaspoon ground black pepper",
      "Shredded Monterey Jack cheese",
      "1 tablespoon olive oil",
    ],
  },
  {
    image: "/assets/recipe/recipy (2).jfif",
    name: "Morok Polawo",
    discription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In excepturi necessitatibus animi officia corrupti laudantium nesciunt saepe rerum dolores corporis odio quae obcaecati doloribus magnam, praesentium aliquam cumque culpa! Iste modi quis totam excepturi? Dolore accusamus, incidunt error ducimus inventore sit eveniet iusto numquam exercitationem ipsam itaque at harum quibusdam nobis fugit beatae distinctio cumque molestias illum reiciendis quisquam enim dolorem. Ex assumenda tempore blanditiis beatae quidem repellat non quos ea, velit, et quo? Quo libero deserunt dolor atque dolore aperiam velit sapiente voluptatum veniam blanditiis? Atque qui iure quaerat rem quia suscipit esse incidunt possimus, quasi laudantium optio temporibus nulla ipsam laborum aliquam fugiat provident, deserunt, voluptas neque praesentium labore sequi. Aspernatur fugiat blanditiis dolorem assumenda debitis explicabo reprehenderit, laborum impedit dolor, modi alias illum dolorum quae culpa nisi corporis? Veniam provident nisi ab eos doloremque iure sequi, magnam cupiditate libero odit, tenetur iste consequatur accusantium, perferendis consectetur similique ipsam praesentium fugiat! Soluta, doloribus sequi! Suscipit magni esse cupiditate labore animi consequuntur dolorum iure quae sit, ullam omnis ad nesciunt nam! Tempore sunt ea temporibus rem pariatur dolor perspiciatis maiores adipisci magnam deserunt facere quibusdam sed impedit velit, reiciendis numquam fugiat delectus quaerat. Labore quas in eveniet earum autem.",
    ingredients: [
      "Sliced avocado",
      "1 bay leaf",
      "1/2 cup bittersweet chocolate chips (I like Ghirardelli)",
      "1 cup black beans",
      "Black Beans",
      "1 (15 oz.) can red kidney beans, drained and rinsed",
      "1 (28 oz.) can crushed tomatoes",
      "Toasted corn or flour tortillas for scooping",
      "Chili",
      "2 teaspoons chili powder (mine is a bit on the hot side)",
      "Chopped fresh cilantro",
      "2 garlic cloves, chopped",
      "1 teaspoon ground coriander",
      "2 teaspoons ground cumin",
      "1/2 teaspoon ground black pepper",
      "Shredded Monterey Jack cheese",
      "1 tablespoon olive oil",
    ],
  },
  {
    image: "/assets/recipe/recipy (3).jfif",
    name: "White Polawo",
    discription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In excepturi necessitatibus animi officia corrupti laudantium nesciunt saepe rerum dolores corporis odio quae obcaecati doloribus magnam, praesentium aliquam cumque culpa! Iste modi quis totam excepturi? Dolore accusamus, incidunt error ducimus inventore sit eveniet iusto numquam exercitationem ipsam itaque at harum quibusdam nobis fugit beatae distinctio cumque molestias illum reiciendis quisquam enim dolorem. Ex assumenda tempore blanditiis beatae quidem repellat non quos ea, velit, et quo? Quo libero deserunt dolor atque dolore aperiam velit sapiente voluptatum veniam blanditiis? Atque qui iure quaerat rem quia suscipit esse incidunt possimus, quasi laudantium optio temporibus nulla ipsam laborum aliquam fugiat provident, deserunt, voluptas neque praesentium labore sequi. Aspernatur fugiat blanditiis dolorem assumenda debitis explicabo reprehenderit, laborum impedit dolor, modi alias illum dolorum quae culpa nisi corporis? Veniam provident nisi ab eos doloremque iure sequi, magnam cupiditate libero odit, tenetur iste consequatur accusantium, perferendis consectetur similique ipsam praesentium fugiat! Soluta, doloribus sequi! Suscipit magni esse cupiditate labore animi consequuntur dolorum iure quae sit, ullam omnis ad nesciunt nam! Tempore sunt ea temporibus rem pariatur dolor perspiciatis maiores adipisci magnam deserunt facere quibusdam sed impedit velit, reiciendis numquam fugiat delectus quaerat. Labore quas in eveniet earum autem.",
    ingredients: [
      "Sliced avocado",
      "1 bay leaf",
      "1/2 cup bittersweet chocolate chips (I like Ghirardelli)",
      "1 cup black beans",
      "Black Beans",
      "1 (15 oz.) can red kidney beans, drained and rinsed",
      "1 (28 oz.) can crushed tomatoes",
      "Toasted corn or flour tortillas for scooping",
      "Chili",
      "2 teaspoons chili powder (mine is a bit on the hot side)",
      "Chopped fresh cilantro",
      "2 garlic cloves, chopped",
      "1 teaspoon ground coriander",
      "2 teaspoons ground cumin",
      "1/2 teaspoon ground black pepper",
      "Shredded Monterey Jack cheese",
      "1 tablespoon olive oil",
    ],
  },
  {
    image: "/assets/recipe/recipy (4).jfif",
    name: "Jorda ",
    discription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In excepturi necessitatibus animi officia corrupti laudantium nesciunt saepe rerum dolores corporis odio quae obcaecati doloribus magnam, praesentium aliquam cumque culpa! Iste modi quis totam excepturi? Dolore accusamus, incidunt error ducimus inventore sit eveniet iusto numquam exercitationem ipsam itaque at harum quibusdam nobis fugit beatae distinctio cumque molestias illum reiciendis quisquam enim dolorem. Ex assumenda tempore blanditiis beatae quidem repellat non quos ea, velit, et quo? Quo libero deserunt dolor atque dolore aperiam velit sapiente voluptatum veniam blanditiis? Atque qui iure quaerat rem quia suscipit esse incidunt possimus, quasi laudantium optio temporibus nulla ipsam laborum aliquam fugiat provident, deserunt, voluptas neque praesentium labore sequi. Aspernatur fugiat blanditiis dolorem assumenda debitis explicabo reprehenderit, laborum impedit dolor, modi alias illum dolorum quae culpa nisi corporis? Veniam provident nisi ab eos doloremque iure sequi, magnam cupiditate libero odit, tenetur iste consequatur accusantium, perferendis consectetur similique ipsam praesentium fugiat! Soluta, doloribus sequi! Suscipit magni esse cupiditate labore animi consequuntur dolorum iure quae sit, ullam omnis ad nesciunt nam! Tempore sunt ea temporibus rem pariatur dolor perspiciatis maiores adipisci magnam deserunt facere quibusdam sed impedit velit, reiciendis numquam fugiat delectus quaerat. Labore quas in eveniet earum autem.",
    ingredients: [
      "Sliced avocado",
      "1 bay leaf",
      "1/2 cup bittersweet chocolate chips (I like Ghirardelli)",
      "1 cup black beans",
      "Black Beans",
      "1 (15 oz.) can red kidney beans, drained and rinsed",
      "1 (28 oz.) can crushed tomatoes",
      "Toasted corn or flour tortillas for scooping",
      "Chili",
      "2 teaspoons chili powder (mine is a bit on the hot side)",
      "Chopped fresh cilantro",
      "2 garlic cloves, chopped",
      "1 teaspoon ground coriander",
      "2 teaspoons ground cumin",
      "1/2 teaspoon ground black pepper",
      "Shredded Monterey Jack cheese",
      "1 tablespoon olive oil",
    ],
  },
  {
    image: "/assets/recipe/recipy (5).jfif",
    name: "Maton Breyany",
    discription:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In excepturi necessitatibus animi officia corrupti laudantium nesciunt saepe rerum dolores corporis odio quae obcaecati doloribus magnam, praesentium aliquam cumque culpa! Iste modi quis totam excepturi? Dolore accusamus, incidunt error ducimus inventore sit eveniet iusto numquam exercitationem ipsam itaque at harum quibusdam nobis fugit beatae distinctio cumque molestias illum reiciendis quisquam enim dolorem. Ex assumenda tempore blanditiis beatae quidem repellat non quos ea, velit, et quo? Quo libero deserunt dolor atque dolore aperiam velit sapiente voluptatum veniam blanditiis? Atque qui iure quaerat rem quia suscipit esse incidunt possimus, quasi laudantium optio temporibus nulla ipsam laborum aliquam fugiat provident, deserunt, voluptas neque praesentium labore sequi. Aspernatur fugiat blanditiis dolorem assumenda debitis explicabo reprehenderit, laborum impedit dolor, modi alias illum dolorum quae culpa nisi corporis? Veniam provident nisi ab eos doloremque iure sequi, magnam cupiditate libero odit, tenetur iste consequatur accusantium, perferendis consectetur similique ipsam praesentium fugiat! Soluta, doloribus sequi! Suscipit magni esse cupiditate labore animi consequuntur dolorum iure quae sit, ullam omnis ad nesciunt nam! Tempore sunt ea temporibus rem pariatur dolor perspiciatis maiores adipisci magnam deserunt facere quibusdam sed impedit velit, reiciendis numquam fugiat delectus quaerat. Labore quas in eveniet earum autem.",
    ingredients: [
      "Sliced avocado",
      "1 bay leaf",
      "1/2 cup bittersweet chocolate chips (I like Ghirardelli)",
      "1 cup black beans",
      "Black Beans",
      "1 (15 oz.) can red kidney beans, drained and rinsed",
      "1 (28 oz.) can crushed tomatoes",
      "Toasted corn or flour tortillas for scooping",
      "Chili",
      "2 teaspoons chili powder (mine is a bit on the hot side)",
      "Chopped fresh cilantro",
      "2 garlic cloves, chopped",
      "1 teaspoon ground coriander",
      "2 teaspoons ground cumin",
      "1/2 teaspoon ground black pepper",
      "Shredded Monterey Jack cheese",
      "1 tablespoon olive oil",
    ],
  },
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Recipes>
) {
  res.status(200).json(recipes);
}
